### ISSUE TITLE
[Bug]: Minecraft Farbric fails to install

### ISSUE THREAD

**Issue by hafometh88** [pelican-eggs/minecraft#24]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

Minecraft Fabric

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and start it

### Actual Behavior

The installation says it was successful, but I think the server fails to download and it does not start

```
Downloading Minecraft server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:89)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at net.fabricmc.installer.util.Utils.openUrl(Utils.java:145)
        at net.fabricmc.installer.util.Utils.readString(Utils.java:90)
        at net.fabricmc.installer.util.FabricService.queryJsonSubstitutedMaven(FabricService.java:44)
        at net.fabricmc.installer.util.LauncherMeta.getVersionsFromUrl(LauncherMeta.java:46)
        at net.fabricmc.installer.util.LauncherMeta.load(LauncherMeta.java:39)
        at net.fabricmc.installer.util.LauncherMeta.getLauncherMeta(LauncherMeta.java:31)
        at net.fabricmc.installer.server.MinecraftServerDownloader.getVersionMeta(MinecraftServerDownloader.java:62)
        at net.fabricmc.installer.server.MinecraftServerDownloader.getServerDownload(MinecraftServerDownloader.java:72)
        at net.fabricmc.installer.server.MinecraftServerDownloader.isServerJarValid(MinecraftServerDownloader.java:58)
        at net.fabricmc.installer.server.MinecraftServerDownloader.downloadMinecraftServer(MinecraftServerDownloader.java:37)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:84)
        at net.fabricmc.installer.Main.main(Main.java:87)
```

After launching:

```
[10:40:39] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
[10:40:39] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
Caused by: java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
        at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:212)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
```

### Steps To Reproduce

1. Install a Fabric server
2. Try to launch it

### Install logs

https://ptero.co/fehusowuse

**Comment by gOOvER** [comment]
looks like a connection problem and not an egg problem

`Caused by: java.net.SocketTimeoutException: Read timed out`

**Comment by hafometh88** [comment]
@gOOvER hmmm, but everything downloaded fine until this point in the install script

**Comment by hafometh88** [comment]
nvm, it was a networking issue in my wireguard tunnel.

Packet fragmentation was causing the reset. The VPN tunnel is introducing overhead that causes packets to exceed the MTU, leading to dropped packets.

I resolved it by enabling MSS clamping on my wireguard server

`iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu`
